name: Create GitHub Secret

on:
  workflow_dispatch:
    inputs:
      secret_key:
        type: string
        description: "Name of the secret's key"
      secret_value:
        type: string
        description: "Value of the secret"

jobs:
  create_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mask secret value
        run: echo "::add-mask::${{ inputs.secret_value }}"

      - name: Send Data to Port
        env:
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
        run: |
          curl -X POST "https://api.getport.io/v1/entities" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d '{
              "blueprintIdentifier": "basic_githubsecret",
              "identifier": "${{ inputs.secret_key }}",
              "title": "${{ inputs.secret_key }}",
              "properties": {
                "secret_key": "${{ inputs.secret_key }}",
                "secret_value": "${{ inputs.secret_value }}"
              }
            }'
